models/Product.php
<?php
/**
 * Created by PhpStorm.
 * User: Віталій
 * Date: 21.02.2017
 * Time: 21:14
 */

namespace app\models;
use yii\db\ActiveRecord;


class Product extends ActiveRecord{
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    public static function tableName(){
        return 'product';
    }

    public function getCategory(){
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

}

controllers/CartController.php
<?php


namespace app\controllers;
use app\models\Product;
use app\models\Cart;

use app\models\Order;
use app\models\OrderItems;
use Yii;


class CartController extends AppController{

    public function actionAdd(){
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        $product = Product::findOne($id);
        if(empty($product)) return false;
        $session =Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        if( !Yii::$app->request->isAjax ){
            return $this->redirect(Yii::$app->request->referrer);
        }
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionClear(){
        $session =Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session =Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionShow(){
        $session =Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }


    public function actionView(){
        $session = Yii::$app->session;
        $session->open();
        $this->setMeta('Корзина');
        $order = new Order();
        if( $order->load(Yii::$app->request->post()) ){
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            if($order->save()){
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят. Менеджер вскоре свяжется с Вами.');
                Yii::$app->mailer->compose('order', ['session' => $session])
                    ->setFrom(['vetal.lemon95@mail.ru' => 'shop'])
                    ->setTo($order->email)
                    ->setSubject('Заказ')
                    ->send();
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error', 'Ошибка оформления заказа');
            }
        }
        return $this->render('view', compact('session', 'order'));
    }

    protected function saveOrderItems($items, $order_id){
        foreach($items as $id => $item){
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }

} 

controllers/CategoryController.php
<?php
/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 08.05.2016
 * Time: 10:00
 */

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use yii\data\Pagination;
use Yii;


class CategoryController extends AppController{

    public function actionIndex(){
        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();
        $this->setMeta('Yii-Shop');
        return $this->render('index', compact('hits'));
    }

    public function actionView($id){
        $id = Yii::$app->request->get('id');
        $category = Category::findOne($id);
        if(empty($category))
            throw new \yii\web\HttpException(404, 'Такої категорії не має');
        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 6, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();;
        $category = Category::findOne($id);
        $this->setMeta('Yii-Shop | ' . $category->name, $category->keywords, $category->description);
        return $this->render('view', compact('products','category','pages'));
    }
    public function actionSearch(){
        $q = trim(Yii::$app->request->get('q'));
        $this->setMeta(' Поиск: ' . $q);
        if(!$q)
            return $this->render('search');
        $query = Product::find()->where(['like', 'name', $q]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('search', compact('products', 'pages', 'q'));
    }

}

controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 09.05.2016
 * Time: 10:50
 */

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use Yii;

class ProductController extends AppController{

    public function actionView($id){
        $id = Yii::$app->request->get('id');
        $product = Product::findOne($id);
        if(empty($product))
            throw new \yii\web\HttpException(404, 'Такого товару не існує');

//        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        return $this->render('view', compact('product'));
    }

} 

views/product/view.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use ckarjun\owlcarousel\OwlCarouselWidget;

?><div class="col-sm-3 thumbnail">
    <ul class="nav nav-pills nav-stacked">
        <?= \app\components\MenuWidget::widget(['tpl'=>'menu']) ?>
    </ul>
</div>
<?php
$mainImg = $product->getImage();
$gallery = $product->getImages();
?>
<div class="col-sm-9 padding-right thumbnail">
    <h1><?=$product->name  ?></h1>
   <div class="col-sm-5">
       <?= Html::img($mainImg->getUrl(), ['alt' => $product->name,'class'=>'img-responsive'])?>

<?php
OwlCarouselWidget::begin([
    'container' => 'div',
    'containerOptions' => [
        'id' => 'slide',
        'class' => 'slider'
    ],
    'pluginOptions' => [
        'autoPlay' => 3000,
        'items' => 1,
        'itemsDesktop' => [84],
        'itemsDesktopSmall' => [84]
    ]
]);
?>


<div id="slide" class=" owl-theme slider">
           <?php $count = count($gallery);  foreach($gallery as $img): ?>

               <?= Html::img($img->getUrl('84'), ['alt' => ''])?>

           <?php endforeach;?>
</div>

<?php OwlCarouselWidget::end();?>

   </div>
<div class="col-sm-7">
    <div class="product-information"><!--/product-information-->

        <h2><?= $product->name?></h2>


									<span>
									<span><?= $product->price?> UAH</span>
									<label>Кількість:</label>
									<input type="text" value="1" id="qty" />
									<a href="<?= \yii\helpers\Url::to(['cart/add', 'id' => $product->id])?>" data-id="<?= $product->id?>" class="btn btn-default add-to-cart cart">
                                      <span class="glyphicon glyphicon-shopping-cart"></span>
                                      До корзини
                                    </a>
								</span>


        <p><b>Категорія:</b> <a href="<?= \yii\helpers\Url::to(['category/view', 'id' => $product->category->id]) ?>"><?= $product->category->name?></a></p>
    </div><!--/product-information-->






</div>
   <div class="col-sm-12">

           <ul class="nav nav-tabs">
               <li class="active"><a data-toggle="tab" href="#description">Детальний опис</a></li>
               <li><a data-toggle="tab" href="#comments">Коментарі</a></li>

           </ul>

           <div class="tab-content">
               <div id="description" class="tab-pane fade in active">
                   <?= $product->content?>
               </div>
               <div id="comments" class="tab-pane fade">
                   comments
               </div>

           </div>


   </div>
</div>